#!/bin/bash
#
# $Id$
#
# Copyright (C) 2004 Guillem Jover <guillem@debian.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA.
#

. archive-lib

# Find old cruft and move it to rejected

mkdir -p $rejected_daily_dir

find $incoming_dir -mindepth 1 -ctime -7 | \
  tee -a $log_dir/clean-`date -I`.log | \
  xargs -n1 -i% mv "%" $rejected_daily_dir

