#!/bin/bash
#
# $Id$
#
# Copyright (C) 2003, 2004 Guillem Jover <guillem@debian.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA.
#

#
# Requires: apt-utils
#

# Import library

. archive-lib

#
# Main
#

echo "-> Regenerating .changes files list..."
find $pool_dir -name '*.changes' > $cache_dir/changes.list

echo "-> Regenarating file lists..."
find $pool_dir -name "*_all.deb" -o -name "*_all.udeb" > $cache_dir/files_all.list
for arch in $arch_list; do
  if [ $arch != source ]; then
    echo " -> Listing $arch debs"
    (
      find $pool_dir -name "*_$arch.deb" -o -name "*_$arch.udeb"
      cat $cache_dir/files_all.list
    ) > $cache_dir/files_$arch.list
  fi
done

echo "-> Regenerating indexes..."
apt-ftparchive generate $apt_config

