#!/bin/bash
#
# Copyright © 2003-2007 Guillem Jover <guillem@debian.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#

#
# Requires: apt-utils
#

# Import library

. archive-lib

#
# Main
#

echo_time "-> Regenerating Packages and Sources files..."
apt-ftparchive generate $apt_config

echo_time "-> Regenerating Releases files..."
for suite in $suite_list; do
  # FIXME: hardcoded check
  if [ $suite = experimental ]; then
    release_auto='-o APT::FTPArchive::Release::NotAutomatic="yes"'
  else
    release_auto=
  fi

  apt-ftparchive -c $apt_config \
    -o APT::FTPArchive::Release::Suite="$suite" \
    -o APT::FTPArchive::Release::Codename="$(get_suite_codename $suite)" \
    -o APT::FTPArchive::Release::Architectures="$(get_suite_arches $suite)" \
    -o APT::FTPArchive::Release::Components="$(get_suite_sections $suite)" \
    $release_auto \
    release $dists_dir/$suite \
    > $dists_dir/$suite/.Release
  rm -f $dists_dir/$suite/Release
  mv -f $dists_dir/$suite/{.Release,Release}
  gpg -a --yes -u $archive_keyid $archive_keyrings -b \
    -o $dists_dir/$suite/Release.gpg $dists_dir/$suite/Release
done

echo_time "-> Done."
