#!/bin/bash
#
# $Id$
#
# Copyright (C) 2004 Guillem Jover <guillem@debian.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA.
#

. archive-lib

# Main

changes_uniq ()
{
  while read package arch version; do
    if [ "$package" != "$g_package" ] || [ "$arch" != "$g_arch" ]; then
      printf "%-20s %-20s %-20s\n" $g_package $g_arch $g_version
      g_package=$package
      g_version=$version
      g_arch=$arch
    else
      if dpkg --compare-versions $version le $g_version; then
        g_package=$package
        g_version=$version
        g_arch=$arch
      fi
    fi
  done
}

echo "-> Doing archive statistics"

find $pool_dir -name '*.changes' | (
while read f_changes; do
  dir=`dirname $f_changes`
  changes=`basename ${f_changes%.changes}`
  package=`echo $changes | cut -d_ -f1`
  version=`echo $changes | cut -d_ -f2`
  arch=`echo $changes | cut -d_ -f3`

  printf "%-20s %-20s %-20s\n" $package $arch $version
done
) | sort | changes_uniq > $cache_dir/stats.list

