#!/bin/bash
#
# $Id$
#
# Copyright (C) 2004 Guillem Jover <guillem@debian.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA.
#

#
# Requires: awk
#

# Import configuration

. archive-lib

target_arch=$1

dir=$dists_dir/unstable/main
target_arch_dir=$obsolete_dir/$target_arch

echo "-> Obsoleting arch: $target_arch"

cat $cache_dir/$target_arch.list | while read file
do
  echo " -> Obsoleting: $file"
  target_dir=`dirname $file`
  mkdir -p $target_arch_dir/$target_dir
  mv $pool_dir/$file $target_arch_dir/$target_dir
done

echo " done."

