#!/bin/bash
#
# $Id$
#
# Copyright (C) 2004, 2005 Guillem Jover <guillem@debian.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA.
#

# Import configuration

. archive-lib

LANG=C

cd $cache_dir

echo "-> Generating obsolete lists..."
for arch in $(get_archive_arches); do
  echo " -> Generating obsolete lists... [$arch]"
  cat changes_$arch.list | changes_newest > changes_${arch}_new.list
  sort changes_$arch.list changes_${arch}_new.list | \
    uniq -u > changes_${arch}_obs.list
  sort changes_${arch}_new.list changes_${arch}_obs.list > \
    changes_${arch}_full.list

  if cmp -s changes_$arch.list changes_${arch}_full.list; then
    echo "  -> Ok: Obsolete list [$arch], proceeding ..."
    cat changes_${arch}_obs.list | while read package suite arch version changes_file; do
      files=`changes_strip < $changes_file | fetch_files`
      binfiles=`echo "$srcfiles" | grep 'deb$'`

      echo "  -> Obsoleting: $package-$version ($suite) [$arch]"
      echo "   -> Changes file: ${changes_file##*/}"
      echo "   -> Binary files: $files"
    done
  else
    echo "  -> Error: Obsolete list [$arch], manual intervetion needed."
  fi
done
echo "-> Done."

