#!/bin/bash
#
# archive-lib
#
# Requires: procmail (formail)

# Import configuration

. archive-lib

create_apt_config ()
{
  cat > $apt_config <<-HERE
	Default {
	  Packages::Compress ". gzip bzip2";
	  Sources::Compress ". gzip bzip2";
	};

	Dir {
	  ArchiveDir	"$archive_dir";
	  OverrideDir	"$indices_dir";
	};

	TreeDefault {
	  Directory "pool/";
	};
HERE

  for suite in $suite_list; do
    cat >> $apt_config <<-HERE
	
	Tree "dists/$suite" {
	  Sections		"$section_list";
	  Architectures		"$arch_list";
	  BinCacheDb		"$suite.db";
	};
HERE
  done
}

create_repo ()
{
  if [ ! -d $incoming_dir ]; then
    mkdir -p $incoming_dir
  fi

  for suite in $suite_list; do
     for section in $section_list; do
      for arch in $arch_list; do
         if [ $arch = source ]; then
          path_dir=$dists_dir/$suite/$section/$arch
        else
          path_dir=$dists_dir/$suite/$section/binary-$arch
        fi
        mkdir -p $path_dir
      done
    done
  done

  if [ ! -d $indices_dir ]; then
    mkdir -p $indices_dir
    touch $indices_dir/override
    touch $indices_dir/override.extra
  fi

  mkdir -p $queue_dir
  mkdir -p $unchecked_dir
  mkdir -p $accepted_dir
  mkdir -p $rejected_dir
  mkdir -p $byhand_dir

  if [ ! -d $pool_dir ]; then
    mkdir -p $pool_dir
  fi
}


create_repo
create_apt_config

