#!/bin/bash
#
# Copyright © 2007 Guillem Jover <guillem@debian.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#

# Import library

. archive-lib

#
# Main
#

set -e

idx_dir=indices/files/components
# FIXME: Hardcoded stuff
idx_suite=unstable
idx_file=suite-$idx_suite.list
idx_filtered_file=mirror_${idx_suite}_all.list

cd $cache_dir

echo_time '-> Mirroring from master server ...'

echo_time ' -> Syncing arch:all packages list ...'
rsync -v \
  rsync://$debian_archive/$idx_dir/$idx_file.gz ./

echo_time " -> Filtering arch:all packages ..."
zcat $idx_file.gz | sed 's,^\./,,' | grep '^pool/main/.*/.*_all.u*deb' \
  | sort >$idx_filtered_file

cd $archive_dir

echo_time ' -> Syncing arch:all packages ...'
rsync -vm --times --links --hard-links \
  --files-from $cache_dir/$idx_filtered_file \
  --max-delete=0 \
  rsync://$debian_archive/ ./

echo_time ' -> Removing obsolete arch:all packages ...'
# FIXME: Hardcoded pool_dir
find pool -type f | sort >$cache_dir/pool.list
diff -u $cache_dir/pool.list $cache_dir/$idx_filtered_file \
  | tail -n +2 | grep '^-' | cut -c2- >$cache_dir/pool.removals

# Mass removal protection!
if [ `wc -l $cache_dir/pool.removals | cut -d\  -f1` -gt 1000 ]; then
  echo_time 'error: mass removal in progress, aborting.'
  exit 1
else
  xargs rm -f <$cache_dir/pool.removals
fi

echo_time '-> Done.'

