#!/bin/bash
#
# Copyright © 2003, 2004, 2005 Guillem Jover <guillem@debian.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#

# Import library

. archive-lib

#
# Main
#

echo_time "-> Collecting files"

echo_time " -> Collecting override files"
d=sid
a=unstable
for c in main main.src main.debian-installer extra.main; do
  wget -q -N http://$debian_archive/indices/override.$d.$c.gz -O $indices_dir/override.$a.$c.gz
  gunzip -f $indices_dir/override.$a.$c.gz
  ln -f -s $indices_dir/override.$a.$c $indices_dir/override.unreleased.$c
  # FIXME: DAK hardcodes this ...
  ln -f -s $indices_dir/override.$a.$c $indices_dir/override.experimental.$c
done

cd $cache_dir

echo_time " -> Collecting Sources files"
wget -q -N http://$debian_archive/dists/unstable/main/source/Sources.bz2
bunzip2 -c Sources.bz2 > Sources
echo_time " -> Collecting hurd-i386 binary files"
wget -q -N http://$debian_archive/dists/unstable/main/binary-hurd-i386/Packages.bz2 -O Packages-unstable.hurd-i386.bz2
bunzip2 -c Packages-unstable.hurd-i386.bz2 > Packages-unstable.hurd-i386

echo_time " -> Collecting Packages files"
for arch in $(get_suite_arches unreleased); do
  if [ $arch != source ]; then
    echo "  -> Architecture: $arch"
    cat $dists_dir/unreleased/main/binary-$arch/Packages > Packages.$arch
    # FIXME: diff unstable from unreleased to get the unofficial arch list
    if [ $arch = hurd-i386 ]; then
      cat Packages-unstable.hurd-i386 >> Packages.$arch
    fi
  fi
done

echo_time "-> Done."

