#!/bin/bash
#
# Copyright © 2004, 2006, 2007 Guillem Jover <guillem@debian.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#

. archive-lib

# Main

log stats "-> Doing archive statistics"

for arch in $(get_archive_arches); do
  log stats " -> Source packages in: $arch"
  cut -f2 -d\  $cache_dir/changes_$arch.list | sort | uniq -c | logpipe stats

  # Special case unreleased as it is the place holder for arch specific hacks
  log stats " -> Type of specific hacks (unreleased) in: $arch"
  grep '[^ ]\+ unreleased' $cache_dir/changes_$arch.list | cut -f4 -d\  \
    | sed -re 's/\+b[0-9]+//;s/\.[0-9]+$//;s/.*\+([a-z]*)$/\1/;s/^[0-9].*/<version>/' \
    | sort | uniq -c | logpipe stats

  # Print the .changes files for the unreleased suite
  grep '[^ ]\+ unreleased' $cache_dir/changes_$arch.list | cut -f5 -d\  \
    | xargs cat | logpipe changes-$arch >/dev/null
done

log stats "-> Done."
